name: KMP branch build

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
#     - name: Build with Gradle
#       run: |
#         ./gradlew wrapper --gradle-version 8.7.2 --distribution-type bin
#         ./gradlew build
    - name: Build snapshot
      run: ./gradlew publishAllPublicationsToMavenCentralRepository --no-configuration-cache
