name: Android CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle wrapper
      run: gradle wrapper --gradle-version 8.5 --distribution-type all
    - name: Build with Gradle
      run: ./gradlew build
